// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-11-27 11:24:25.3951586 +0800 CST m=+0.063830401

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Market Monitor 简易API文档",
        "title": "Market Monitor API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "ink",
            "url": "http://jiangink.github.com",
            "email": "jiangink.cn@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "1.0"
    },
    "host": "localhost:8000",
    "basePath": "/api/v1",
    "paths": {
        "/auth/signin": {
            "post": {
                "description": "通过邮箱密码登录账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "账号登录",
                "operationId": "auth.signin",
                "parameters": [
                    {
                        "description": "账号登录请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.SigninRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"code\": 2000001, msg:\"请求处理成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"status\":400, \"code\": 4000001, msg:\"请求参数有误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"status\":401, \"code\": 4010001, msg:\"账号或密码有误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"status\":500, \"code\": 5000001, msg:\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/signout": {
            "post": {
                "description": "用户账号注销",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "账号注销",
                "operationId": "auth.signout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "认证 Token 值",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"code\": 2000001, msg:\"请求处理成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"status\":500, \"code\": 5000001, msg:\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "通过邮箱密码注册账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "账号注册",
                "operationId": "auth.signup",
                "parameters": [
                    {
                        "description": "账号注册请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"code\": 2000001, msg:\"请求处理成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"status\":400, \"code\": 4000001, msg:\"请求参数有误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"status\":500, \"code\": 5000001, msg:\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "获取当前登录用户基本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "认证 Token 值",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"code\": 2000001, msg:\"请求处理成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"status\":500, \"code\": 5000001, msg:\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/avatar": {
            "patch": {
                "description": "修改当前登录用户头像",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "修改用户头像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "认证 Token 值",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户头像请求参数",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"code\": 2000001, msg:\"请求处理成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"status\":500, \"code\": 5000001, msg:\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/name": {
            "patch": {
                "description": "修改当前登录用户昵称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "编辑用户昵称",
                "parameters": [
                    {
                        "type": "string",
                        "description": "认证 Token 值",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改用户名称请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.EditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"code\": 2000001, msg:\"请求处理成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"status\":500, \"code\": 5000001, msg:\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/pass": {
            "patch": {
                "description": "修改当前登录用户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "认证 Token 值",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改用户密码请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.PassRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"code\": 2000001, msg:\"请求处理成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"status\":500, \"code\": 5000001, msg:\"服务器内部错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.EditRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.PassRequest": {
            "type": "object",
            "required": [
                "newPass",
                "oldPass"
            ],
            "properties": {
                "newPass": {
                    "type": "string"
                },
                "oldPass": {
                    "type": "string"
                }
            }
        },
        "v1.SigninRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "v1.SignupRequest": {
            "type": "object",
            "required": [
                "accountPass",
                "confirmPass",
                "email"
            ],
            "properties": {
                "accountPass": {
                    "type": "string"
                },
                "confirmPass": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
